### ISSUE TITLE
[Feat] 예약 도메인 설계

### ISSUE THREAD

**Issue by wooseok50** [How-about-over-there/server#4]
## Description

예약 서비스의 도메인을 설계합니다
## TODO

- [x] reservation Entity 설계
- [x] 예약 상태 Enum 생성
- [x] DB 연결 (postgresql)
